# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 53369667c8b5c6ad56adcda3705a7efdba5fe992683597fc0f3d165813085caa2c63c1621e7accec7ce4347852d0da6fdaaa4b4fc92d76356dd93f816049ceb0

test:
  secret_key_base: 7c2cc0c2839a6b377652f917b2875834ea7a20ff5a6a4e923bdc176e2d3cca35c0d45864f746401e7f9cc7393131b5d1ac8b009b8c0dd4a59164348212765748

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
